---

- name: Deploy the OSP Map plugin.
  sudo: True
  hosts: webservers

  vars:
    app_dir: /usr/local/projects/osp-map
    repo: https://github.com/overview/osp-map.git
    port: 3001

  roles:
    - common
    - nodejs

  tasks:

  - name: Deploy osp-map
    register: code
    git:
      repo: "{{ repo }}"
      dest: "{{ app_dir }}"

  - name: Install npm dependencies
    command: npm install
    when: code.changed
    args:
      chdir: "{{ app_dir }}"

  - name: Build the front-end application
    command: grunt compile:min
    when: code.changed
    args:
      chdir: "{{ app_dir }}"

  - name: Start the app
    command: pm2 startOrReload app.json
    when: code.changed
    args:
      chdir: "{{ app_dir }}"
    environment:
      PORT: "{{ port }}"
      NODE_ENV: production
