---

- name: Deploy the OSP Map plugin.
  hosts: webservers

  vars:
    app_dir: /home/ubuntu/src/osp-map
    repo: https://github.com/overview/osp-map.git
    branch: feature/bb-filter
    port: 3001
    node_env: production

  roles:
    - common
    - nginx
    - nodejs
