---

- name: Deploy Overview stupid entity detector
  sudo: True
  hosts: webservers

  vars:
    app_dir: /home/ubuntu/overview-stupid-entities
    repo: https://github.com/overview/overview-stupid-entities.git
    port: 3001
    node_env: production

  roles:
    - common
    - nginx
    - nodejs

  tasks:

  - name: Deploy overview-stupid-entities
    register: code
    git:
      repo: "{{ repo }}"
      dest: "{{ app_dir }}"

  - name: Install npm dependencies
    command: npm install
    when: code.changed
    args:
      chdir: "{{ app_dir }}"

  - name: Build the front-end application
    command: ./node_modules/.bin/gulp dist
    when: code.changed
    args:
      chdir: "{{ app_dir }}"

  - name: Start the app
    command: pm2 startOrReload app.json -i max
    args:
      chdir: "{{ app_dir }}"
    environment:
      PORT: "{{ port }}"
      NODE_ENV: "{{ node_env }}"
