---
# Install Node.js and global packages.

- name: Add the node PPA
  apt_repository:
    repo: ppa:chris-lea/node.js
    update_cache: yes

- name: Install Node.js
  apt:
    pkg: nodejs
    state: latest

- name: Install global npm modules
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - coffee-script
    - pm2
    - grunt-cli

# TODO
# start vs restart
# deploy multiple apps on different ports
