---
# Install Node.js and global packages.

- name: Add the node PPA
  apt_repository:
    repo: ppa:chris-lea/node.js
    update_cache: yes

- name: Install Node.js
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - git
    - nodejs

- name: Install global npm modules
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - coffee-script
    - pm2
    - grunt-cli
